# Generated by Django 4.2.5 on 2023-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_API', '0002_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgs',
            name='pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
