# Generated by Django 4.2.5 on 2023-09-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_API', '0003_imgs_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
