# Generated by Django 4.2.5 on 2023-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_API', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
