# Generated by Django 4.1.1 on 2023-09-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_API', '0005_image_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgs',
            old_name='pic_url',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='imgs',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
