# Generated by Django 4.1.1 on 2023-09-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Img_API', '0007_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imgs',
        ),
    ]
