# Generated by Django 4.1.1 on 2023-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_API', '0010_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
