# Generated by Django 4.1.1 on 2023-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Img_API', '0014_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgs',
            name='pic',
        ),
        migrations.AddField(
            model_name='imgs',
            name='pic',
            field=models.ManyToManyField(to='Img_API.imagefile'),
        ),
    ]
